### ISSUE TITLE
TLSH distance metric appears to violate triangle inequality

### ISSUE THREAD

**Issue by dmbaggett** [trendmicro/tlsh#130]
Using v4.11.2 of tlsh (last git commit 74efd09a47aecb12f4457b542ebc21d098f901b1) I'm seeing cases where three TLSH hashes appear to violate the triangle inequality, leading to inconsistent search results from metric tree data structure like VP trees. An example:

x = 'T11B735492E6411D2A067795F5D1236BBCE7E94041AB0245F0B0AE35379B8FCA14AB73FC'
y = 'T12F836353E6421D2E493790F9C2329FA8E3D64156A71245E4B0AE35375B8FCA14AB33FC'
z = 'T1879374A3A6416D2E493790B9C2729FA8E3D64116971241E4F4AE34371B8FCD14EB72FC'

d(x,z) (85) > d(x,y) (38) + d(y,z) (24)

Here is a Python script that reproduces this. I did verify that hamming distance between the hex digests for these does adhere to the triangle inequality. (I've attached it as a .txt file since Github doesn't seem to allow attachment of .py files.)

[triangle_inequality_violation.txt](https://github.com/trendmicro/tlsh/files/10969302/triangle_inequality_violation.txt)

**Comment by jonjoliver** [comment]
Hi dmbaggett

Yes - the tlsh distance function does not obey the triangle inequality.
Tlsh distance was defined back in 2013 before quite a lot of hardware support came for metrics which satisfy the triangle inequality. The discrepancies were introduced due to experiments in adversarial environments.
These experiments are described in http://tlsh.org/papersDir/Design_TLSH_2021.pdf

We could create a new security LSH which satisfies the triangle inequality to make search more efficient, but that would be a new hash.

Cheers jono

**Comment by SilverBut** [comment]
Hi jonjoliver,

I'm reading *HAC-T and Fast Search for Similarity in Security* and noticed there is a [Youtube](https://www.youtube.com/watch?v=wMt0mVkhRA0) presentation about it. However, it says TLSH can be searched in a tree, and indicates the distance do obey the triangle inequality:

![Image](https://github.com/user-attachments/assets/05420042-e271-40d9-99f4-1be88492da30)

I'm not quite familiar with data mining. Is the `dist(SearchItem, TLSH_1)` using algorithm other than TLSH distance?

Thanks.
