### ISSUE TITLE
4.12.0 release

### ISSUE THREAD

**Issue by merces** [trendmicro/tlsh#145]
@jonjoliver Opening up this for discussion. Any other issues on the list we should tackle before 4.12.0 release?

**Comment by jonjoliver** [comment]
Hi @merces 

I previously did a release which had quite a lot of fixes in it.
That release was questioned by I think 2 people who requested that changes come in smallish packages.
That way they can check the change - and merge it into their version - or reject the change as not being relevant to them.

Lets look at issues / pull requests we can put together (especially if they are related), but avoid creating a monster release.

Cheers jono

**Comment by jonjoliver** [comment]
Lets create a release for 4.12.0 as it exists today - the README.md / Change_History.md / version numbers in CMakeLists.txt are consistent with the code.

Lets put the following in a 4.12.1
 Remove call to sprintf() to avoid warnings #146 
  py_ext: use PyVarObject_HEAD instead of PyObject_HEAD_INIT #141 
  Build: Define default options only on "default"#138
 Bug Fix+Portability: Improve portability by integral division #136

**Comment by jonjoliver** [comment]
If we agree with the 4.12.1 list then I will modify README.md / Change_History.md / version numbers in CMakeLists.txt  to document that.

**Comment by merces** [comment]
Alright. Sounds good to me! :)

**Comment by sunxingxing** [comment]
> Sure, sounds good to me! I've already renamed the milestone to 4.12.1 and added the PRs from your list to it. ;)

So could you make a tag of 4.12.0  or make it  a released version.

**Comment by merces** [comment]
@sunxingxing v4.12.0 is out! :) thanks @jonjoliver!
