### ISSUE TITLE
CMake build is broken for Windows vs2019

### ISSUE THREAD

**Issue by Pox2** [trendmicro/tlsh#65]
Hi,

CMake fails on d5e149aecb59c019a75c7839715041e89380249a with:

```
CMake Warning (dev) at CMakeLists.txt:155 (add_subdirectory):
  The source directory

    F:/external/tlsh/Windows

  does not contain a CMakeLists.txt file.
```

**Comment by jonjoliver** [comment]
Hi Pox2

Thanks - I will chase this issue down

cheers
jono

**Comment by Pox2** [comment]
You should have a PR coming this week

**Comment by jonjoliver** [comment]
Hi bitwiser73

Thank you!!!
:-)

That is a significant pull request
I will go through that - merging it - in bite sized chunks - making sure it does not break / change behaviour
- the various windows environments
- linux AWS / CentOS / Ubuntu / ...
- Mac

cheers
jono

**Comment by Nirusu** [comment]
Hey jono,

Any updates on the merge? Having the ability to compile the project under newer versions of Visual Studio without converting them or rewriting stuff first would be great, as it's kind of a hassle to automate these parts. Would really appreciate it!

**Comment by jonjoliver** [comment]
Hi Nirusu

I have done some house keeping on the repo
versions 3.14 -> 3.16

I will work through your changes  - and merge many / most in.
I only want to do changes that improve things

Cheers
jono

**Comment by Nirusu** [comment]
Understandably. My usecase right now is to simply build a Python wheel package with the py_ext both for Linux and Windows automatically, because the [one on PyPi](https://pypi.org/project/tlsh/) right now is useless, as it's broken.

The Linux part is easy, the Windows one is a bit more tricky due to the old VS version and the lack of standalone tools. I don't need any other changes, just an somewhat up-to-date build solution for Windows which works with standalone build tools.

I know that you've posted an update in the README.windows on how to update the project by oneself, but yeah, would be convenient to have them right in the repo, right? Especially since VS 2008 isn't the most common Visual Studio version anymore.

But I'm glad you're looking forward to merge them. Good news, thank you!

**Comment by jonjoliver** [comment]
Hi

I was having serious trouble with Cmake on Windows
I am not in the USA
According to https://cmake.org/download/ I am not allowed to have cmake on WIndows.
"This software may not be exported in violation of any U.S. export laws or regulations.  For more information regarding Export Control matters please go to https://www.kitware.com/legal."

So I have built a MinGW windows installation kit
and provided Windows compilation instructions
And provided tlsh.exe as a part of release 4.2.1

Cheers
jono

**Comment by jonjoliver** [comment]
Hi Nirusu

did this resolve your issue?

Cheers
jono

**Comment by jonjoliver** [comment]
We have moved to MinGW as preferred Windows compiler - it gives an environment closer to the Linux / Unix environment.
In addition we are supplying tlsh.exe on github
And created an up to date Python package py-tlsh that has been tested to work on Windows
    https://pypi.org/project/py-tlsh/
