### ISSUE TITLE
How to quickly search for the most similar value from a large number of tlsh values

### ISSUE THREAD

**Issue by qiyeboy** [trendmicro/tlsh#85]
![image](https://user-images.githubusercontent.com/8142734/82855547-2d003b00-9f3e-11ea-986f-8c9a46da155b.png)
https://blog.trendmicro.com/trendlabs-security-intelligence/cluster-of-coins-how-machine-learning-detects-cryptocurrency-mining-malware/

**Comment by alexmi256** [comment]
I too am interested in this.

**Comment by xrkk** [comment]
I also looking for solutions for this one.

**Comment by abgoldberg** [comment]
@alexmi256 @xrkk @qiyeboy Did you guys have any luck with this?

**Comment by alexmi256** [comment]
@abgoldberg I emailed the author but got no response.
I realize that computing real TLSH difference in a database is unlikely (maybe it's possible via stored procedures/functions, even then I have no idea how performant it would be) but a first pass via edit distance seems doable if available natively.
I've found these articles which provide solutions but have have yet to try them out:
https://stackoverflow.com/questions/49779281/string-similarity-with-python-sqlite-levenshtein-distance-edit-distance/49815419#49815419
https://www.red-gate.com/simple-talk/blogs/string-comparisons-in-sql-edit-distance-and-the-levenshtein-algorithm

**Comment by abgoldberg** [comment]
Thanks for the pointers @alexmi256 

I was hoping there's a solution analogous to what can be done for ssdeep, where ngrams or chunks within a tlsh has value could be indexed in an inverted index to narrow the search space. Details for ssdeep are written about here: https://www.virusbulletin.com/virusbulletin/2015/11/optimizing-ssdeep-use-scale

I haven't gotten too much into the internals of TSLH to figure out if a similar strategy is possible here, where given a target TLSH difference, some amount of overlapping n-grams must be found in order to possibly score similar enough. Indexing based on or doing edit distance on the hex-decoded TLSH might be a fruitful direction, but I was hoping someone has already figured this out. :)

**Comment by jonjoliver** [comment]
Hi abgoldberg and others,

I think you can do better than https://www.virusbulletin.com/virusbulletin/2015/11/optimizing-ssdeep-use-scale.

I have written up a technical overview on the issues for fast search
    http://tlsh.org/papers.html
And then how to use fast search to do scalable clustering.
The technical overview points to 2 conference papers that discuss the issues

Cheers
jono

**Comment by jonjoliver** [comment]
We have release a Python version of HAC-T based on
           HAC-T and fast search for similarity in security
           https://tlsh.org/papersDir/COINS_2020_camera_ready.pdf
           2020 International Conference on Omni-layer Intelligent Systems (COINS). IEEE, 2020.

Please check out version 4.10.0 of TLSH
You will find a tlshCluster directory
This also has a simple implementation of Vantage Point Tree search
